// // import React, { ReactNode } from 'react';

// // import Header from '@/components/public/header/Navbar';
// // import Side from '@/components/public/side/Sidebar';
// // import Footer from '@/components/public/footer/Footer';

// // interface LayoutProps {
// //   contents: ReactNode;
// // }

// // const Layout: React.FC<LayoutProps> = ({ contents }) => {
// //   return (
// //     <>
// //       <div className="flex flex-col h-screen">
// //         {/* 헤더 */}
// //         <header className="h-20">
// //           <Header />
// //         </header>

// //         {/* 사이드바 */}
// //         <div className="flex flex-grow overflow-hidden">
// //           {/* 사이드바 */}
// //           <aside className="fixed left-0 w-50 overflow-y-auto z-50">
// //             <Side />
// //           </aside>

// //           {/* 메인 콘텐츠 */}
// //           <main className="flex-grow overflow-y-auto ml-60">
// //             {contents}
// //           </main>
// //         </div>

// //         {/* 푸터 */}
// //         <footer className="flex-shrink-0 h-20">
// //           <Footer />
// //         </footer>
// //       </div>
// //     </>
// //   );
// // }

// // export default Layout;

// "use client";
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

// import Header from '@/components/public/header/Navbar';
// import Aside from '@/components/public/side/Sidebar';
// import Footer from '@/components/public/footer/Footer';
// import { MenuContext } from '@/contexts/MenuContext';
// import { useState } from 'react';

// const [menu, setMenu] = useState('groupware');
// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <MenuContext.Provider value={{menu, setMenu}}>
//       <html lang="en">
//         <body className={inter.className}>
//           <div className="flex">
//             {/* 헤더 */}
//             <header className="h-[5rem] fixed top-0 w-full">
//               <Header />
//             </header>

//             <div className="flex">
//               {/* 사이드바 */}
//               <aside className="left-0 bg-gray-200 w-64 h-[46.5rem] mt-[4rem] px-5 pt-[5rem] shadow">
//                 <Aside />
//               </aside>

//               {/* 메인 콘텐츠 */}
//               <main className="h-[45rem] mt-[4rem] px-5 py-5">
//                 {children}
//               </main>
//             </div>

//             {/* 푸터 */}
//             <footer className="h-auto bottom-0 left-0">
//               <Footer />
//             </footer>
//           </div>
//         </body>
//       </html>
//     </MenuContext.Provider>
//   )
// }
