import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Header from '@/components/public/header/Navbar';
import Aside from '@/components/public/side/Sidebar';
import Footer from '@/components/public/footer/Footer';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (    
      <html lang="en">
        <body className={inter.className}>
          <div className="flex">
            {/* 헤더 */}
            <header className="h-[5rem] fixed top-0 w-full">
              <Header />
            </header>

            <div className="flex">
              {/* 사이드바 */}
              <aside className="left-0 bg-gray-200 w-64 h-[46.5rem] mt-[4rem] px-5 pt-[5rem] shadow">
                <Aside />
                {/* <AsideTest /> */}
              </aside>

              {/* 메인 콘텐츠 */}
              <main className="h-[45rem] mt-[4rem] px-5 py-5">
                {children}
              </main>
            </div>

            {/* 푸터 */}
            <footer className="h-auto bottom-0 left-0">
              <Footer />
            </footer>
          </div>
        </body>
      </html>    
  )
}
