import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Header from '@/components/public/header/Navbar';
import Aside from '@/components/public/side/Sidebar';
import Footer from '@/components/public/footer/Footer';
import { createContext, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

//커스텀 
const Menu = createContext('groupware');

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // 커스텀
  const [menu, setMenu] = useState('groupware'); // 기본 상태 값 설정

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          {/* 헤더 */}
          <header className="h-auto">
            <Header />
          </header>

          <div className="flex">
            {/* 사이드바 */}
            <aside className="left-0 bg-gray-200 w-64 h-[46.5rem] mt-[4rem] px-5 py-5 shadow">
              <Aside />
            </aside>

            {/* 메인 콘텐츠 */}
            <main className="h-[45rem] mt-[4rem] px-5 py-5">
              {children}
            </main>
          </div>

          {/* 푸터 */}
          <footer className="h-auto bottom-0 left-0">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  )
}
